version: "1.55"

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple
    - errcheck
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: "1.25"
